# Grid Search CV -Select the Best HyperParameter for any Classifier 
#Here an example of SVM

# for increasing the accuracy of any model using Grid Search CV - Hyper parametre tuning

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 


In [9]:
#import the data set
dataset = pd.read_csv('advertising')
dataset.head(10)

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0
5  15728773    Male  27.0          58000.0          0
6  15598044  Female  27.0          84000.0          0
7  15694829  Female  32.0         150000.0          1
8  15600575    Male  25.0          33000.0          0
9  15727311  Female  35.0          65000.0          0

In [16]:
x= dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values

In [21]:
#splitting data set in train and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=5)

In [30]:
#next is feature scaling [age , slary in same unit ]
#for this we use standard scaler->uses  techniques to scale down data in stanard normal istribution 
from sklearn.preprocessing import StandardScaler
s= StandardScaler()//#if any where you press shift tab you will get details in popup
x_train=s.fit_transform(x_train)
x_test=s.transform(x_test)#no fit only transform , since fit method is  done only once

In [39]:
#fitting Kernel SVM to traning set [without hyper parameter tuning ]
from sklearn.svm import SVC
classifier =SVC(kernel ='linear',random_state=0)
classifier.fit(x_train,y_train)
#svm[ for linear hyper plane we use linear kernel and for non linear we use rbf as kernel]


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [42]:
#so above in o/p default parameters are use , so we can check if they are working well or not by accuracy 
#so now we will predict
y_pred=classifier.predict(x_test)

In [50]:
 #Making the confusion matrix
from sklearn.metrics import confusion_matrix
cn =confusion_matrix(y_test,y_pred)
cn

array([[54,  4],
       [14, 28]], dtype=int64)

In [63]:
from sklearn.metrics import accuracy_score
accuracy =accuracy_score(y_test,y_pred)

In [64]:
accuracy #its without hyper parameter tuning (kernel selected as linear as heere  we have just 2 feature 
#but its not possible in real worls as there willbe a lot of feaure)

0.82

In [66]:
# To solve actual problem ,for this we use grid search cv , which help to apply different diffrent parameters
from sklearn.model_selection import GridSearchCV
#then you need to select the parameters ,gamma value we can not give very high as it willbecome over fitting condition 
parameters =[{'C':[1,10,100,1000],'kernel':['linear']},
            {'C':[1,10,100,1000],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
#estimator is the classifier model that we created
grid_search= GridSearchCV(estimator= classifier,
                          param_grid=parameters,
                          scoring='accuracy',
                          cv=10,#crossvalidation help to select diffrent train and test data while you are modelling your algorithm
                          n_jobs=-1)
grid_search =grid_search.fit(x_train,y_train)

In [69]:
accuracy =grid_search.best_score_

In [70]:
accuracy

0.9095402298850574

In [71]:
grid_search.best_params_ #so these arethe valuesto be usedinsideyour svc

{'C': 10, 'gamma': 0.3, 'kernel': 'rbf'}

In [72]:
grid_search.best_index_

15

In [76]:
classifier =SVC(kernel ='rbf',gamma= 0.3,)
classifier.fit(x_train,y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.3, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [77]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [79]:
cn =confusion_matrix(y_test,y_pred)
cn

array([[54,  4],
       [ 5, 37]], dtype=int64)

In [80]:
accuracy =accuracy_score(y_test,y_pred)

In [81]:
accuracy

0.91

In [ ]:
#initiall it was 82 % , but after applying grid search cv its 91%
#so you need to diff iff parameters to get better accuracy score